### ISSUE TITLE
页面底部社交平台的 tooptip 中的 capitalize 会让用户名的首字母大写

### ISSUE THREAD

**Issue by bytemain** [Crossbell-Box/xLog#665]
<img width="1105" alt="image" src="https://github.com/Crossbell-Box/xLog/assets/13938334/125a0b8f-c81b-4bb2-9b37-c8fb3019fb52">

如图，这里用户设置的用户名是没有大写的，但是 tooltip 中由于应用了 capitalize 样式(https://tailwindcss.com/docs/text-transform )会让用户名的首字母也变成大写的。

对我个人而言，我是不希望我的用户名首字母被大写的

**Comment by enpitsuLin** [comment]
我觉得可以通过下面的用户自定义CSS来去除这一行为

```css
.capitalize[role="tooltip"]{
    text-transform: none;
}
```
